Repository a2o/snoopy, pull requests merged in 2020-11, with the labels that each got.

#164 GH #113: Store ./configure command used during the build and make it accessible via a new data source
  ChangeLog
  config.h.in
  configure.ac
  etc/snoopy.ini.in
  src/datasource/Makefile.am
  src/datasource/snoopy_configure_command.c
  src/datasource/snoopy_configure_command.h
  src/datasourceregistry.c
  tests/datasource/Makefile.am
  tests/datasource/datasource_snoopy_configure_command.sh
Labels: Component: Core Library, Resolution: Done, Type: Feature

#165 Fix minor spelling errors.
  ChangeLog
  bootstrap.sh
  doc/install/bin/snoopy-install.sh
  src/configfile.c
  src/libsnoopy-debug-addons.c
  src/misc.c
  src/snoopy.h
Labels: Component: Documentation, Resolution: Done

#167 Documentation, build, packaging and installation refactoring
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .travis.yml
  ChangeLog
  Makefile.am
  README.md
  bootstrap.sh
  build/travis.sh
  configure.ac
  configure.scan
  dev-tools/_bootstrap.sh
  dev-tools/build-package-targz.sh
  dev-tools/create-release-commit-and-tag.sh
  dev-tools/import-external-lib.sh
  dev-tools/libexec/get-release-tag.sh
  dev-tools/libexec/get-release-version.sh
  dev-tools/libexec/verify-last-version-in-changelog.sh
  dev-tools/libexec/verify-last-version-in-readme.sh
  dev-tools/publish-release.sh
  dev-tools/submit-to-coverity.sh
  dev-tools/test-build-matrix.sh
  dev-tools/verify-release-tag.sh
  doc/CONTRIBUTING.md
  doc/FAQ.md
  doc/GETTING-SUPPORT.md
  doc/HACKING-INTERNALS.md
  doc/HACKING-OVERVIEW.md
  doc/HACKING-QA.md
  doc/INSTALL.md
  doc/Makefile.am
  doc/RELEASING-HOWTO.md
  doc/internals/Makefile.am
  doc/releasing/RELEASE-HOWTO.txt
  doc/releasing/bin/create-release.sh
  install/install-snoopy.sh
  lib/inih/IMPORT.defs
  lib/inih/LICENSE
  lib/inih/SOURCE.txt
  lib/inih/dev-update.sh
  lib/liblcthw/IMPORT.defs
  lib/liblcthw/SOURCE
  lib/liblcthw/VERSION
  lib/liblcthw/patches/0001-adjust-header-paths.diff
  lib/liblcthw/patches/0002-fix-missing-nulls.diff
  lib/liblcthw/patches/0003-why-is-this-changed.diff
Labels: Component: Documentation, Component: Installation, Component: Packaging, Type: Refactoring

#168 GH #119: Fix symbol leaks
  configure.ac
  configure.scan
  lib/inih/patches/0002-prefix-function-names.diff
  lib/inih/src/ini.h
  lib/liblcthw/patches/0004-prefix-function-names.diff
  lib/liblcthw/src/list.h
  src/datasource/rpname.c
  src/filter/exclude_spawns_of.c
  tests/Makefile.am
  tests/general/Makefile.am
  tests/general/_bootstrap.sh
  tests/general/general-symbol-leaks.sh
Labels: Component: Core Library, Type: Bug

#118 Improve parsing in exclude_spawns_of filter
  src/filter/exclude_spawns_of.c
  tests/filter/Makefile.am
  tests/filter/filter_exclude_spawns_of-mustdrop-multiarg-first.sh
  tests/filter/filter_exclude_spawns_of-mustdrop-multiarg-last.sh
  tests/filter/filter_exclude_spawns_of-mustdrop-multiarg-mid.sh
  tests/filter/filter_exclude_spawns_of-mustdrop-singlearg.sh
  tests/filter/filter_exclude_spawns_of-mustlog-multiarg.sh
  tests/filter/filter_exclude_spawns_of-mustlog-singlearg.sh
Labels: Component: Core Library, Type: Enhancement

#169 GH #117: Add tests for exclude_spawns_of that verify if parent processes with spaces in their name are correctly detected
  tests/bin/Makefile.am
  tests/bin/spaceparent.c
  tests/filter/Makefile.am
  tests/filter/filter_exclude_spawns_of-mustdrop-spaceparent.sh
  tests/filter/filter_exclude_spawns_of-mustlog-spaceparent.sh
Labels: Component: Test Suite, Resolution: Done, Type: Enhancement

#170 GH #145: Enable analysis of PID 1 in filter `exclude_spawns_of`
  src/filter/exclude_spawns_of.c
Labels: Component: Core Library, Resolution: Done, Type: Enhancement

#171 CI: Introduce GitHub workflows for multi-OS build testing
  .github/CODEOWNERS
  .github/workflows/build-qa-autoscan.yml
  .github/workflows/build-qa-config-matrix.yml
  .github/workflows/build-qa-config.h.in.yml
  .github/workflows/build-qa-coverity-scan.yml
  .github/workflows/build-qa-os-matrix.yml
  .github/workflows/build-qa-valgrind.yml
  .github/workflows/install-qa-installfile.yml
  .github/workflows/install-qa-readme.yml
  .gitignore
  .travis.yml
  README.md
  build/coverity-settings.conf.SAMPLE
  build/travis-show-debug-output.sh
  build/travis.sh
  config.h.in
  configure.ac
  configure.scan
  dev-tools/libexec/extract-and-run-install-steps-from-readme.sh
  dev-tools/libexec/get-random-configure-flags.sh
  dev-tools/libexec/get-release-version.sh
  dev-tools/libexec/verify-last-version-in-readme.sh
  dev-tools/submit-to-coverity.conf.SAMPLE
  dev-tools/submit-to-coverity.sh
  doc/HACKING-QA.md
  src/inputdatastorage.c
  src/snoopy.h
  tests/bin/Makefile.am
  tests/datasource/datasource_snoopy_version.sh
  tests/filter/filter_exclude_spawns_of-mustdrop-multiarg-first.sh
  tests/filter/filter_exclude_spawns_of-mustdrop-multiarg-last.sh
  tests/filter/filter_exclude_spawns_of-mustdrop-multiarg-mid.sh
  tests/filter/filter_exclude_spawns_of-mustdrop-singlearg.sh
  tests/general/general-symbol-leaks.sh
Labels: Resolution: Done, Type: Enhancement
